// <auto-generated />
namespace eUni.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Map_Users : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Map_Users));
        
        string IMigrationMetadata.Id
        {
            get { return "201511011639543_Map_Users"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
