// <auto-generated />
namespace eUni.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddconnectionbetweenFileandModule : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddconnectionbetweenFileandModule));
        
        string IMigrationMetadata.Id
        {
            get { return "201601091659003_Add connection between File and Module"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
